# .readthedocs.yaml
version: 2

# Название окружения сборки
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Установка зависимостей
python:
  install:
    - requirements: docs/requirements.txt

# Используем MkDocs
# sphinx:
#   configuration: docs/conf.py  # можно не использовать при MkDocs

mkdocs:
  configuration: docs/mkdocs.yml
